### ISSUE TITLE
Adding ThumbsDownGesture from README

### ISSUE THREAD

**Issue by LastLombax** [andypotato/fingerpose#1]
I was following the readme example for adding a Thumbs Down Gesture Description, but when I execute the app, it breaks when trying to detect any gesture, presenting the following error:

`fingerpose.js:562 Uncaught (in promise) TypeError: Cannot read property 'matchAgainst' of undefined
    at t.value (fingerpose.js:562)
    at estimateHands (index.html:132)`

I've followed how ThumbsUp and Victory Gestures are defined and exported throughout the project and I believe it's something related to fingerpose.js file

**Comment by LastLombax** [comment]
I fixed it, I am dumb, I needed to do `npm build`.

Thanks for this project, by the way, it's really helpful!

**Comment by andypotato** [comment]
Make sure you pass an array of gestures to the constructor or GestureEstimator. Just passing a single object will cause the error you described above.
