### ISSUE TITLE
Possible to load video

### ISSUE THREAD

**Issue by Skorkmaz88** [andypotato/fingerpose#13]
Hello, I wanted to ask if it would be possible to  load video file instead of webcam stream,

**Comment by andypotato** [comment]
Yes you can. Just use the video tag with a `<source src="myvideo.mp4"... >` instead of a webcam stream

**Comment by Skorkmaz88** [comment]
Thanks, 

I also needed to disable these lines of code in the dist example in html, otherwise it was overtaking the video stream :

```
      //const stream = await navigator.mediaDevices.getUserMedia(constraints);    
     //video.srcObject = stream;
```

And to make browser automatically play the video without user interaction I needed to mute the video . Maybe helps someone:

`<video id="pose-video" class="layer" playsinline muted="muted" crossorigin='anonymous'>	 
  <source src="IMG_0003.mp4" >	
</video>`
