### ISSUE TITLE
Tensorflow Models backend error [Solution]

### ISSUE THREAD

**Issue by LastLombax** [andypotato/fingerpose#2]
**Problem**
Recently, Tensorflow.js updated to version 2.0, which contains a few breaking changes. This affected this repository, because it loads _tfjs-core and tfjs-converter_ scripts.
 
I posted an [Issue](https://github.com/tensorflow/tfjs/issues/3352#event-3387531510) on Tensorflow repository and was able to solve my problem.

**Solution**

Update the scripts to either version 1.7.4 (previous version) or to version 2.0 (new version). I kept my scripts with version 1.7.4:

`    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter@1.7.4/dist/tf-converter.min.js"></script>`

  `  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@1.7.4/dist/tf-core.min.js"></script>`

**Comment by andypotato** [comment]
Thanks for the notice.

Actually there's also a new version of the handpose model available which claims increased accuracy. I'll check it out and update the project references accordingly.

**Comment by LastLombax** [comment]
That would be beneficial to my dissertation. Once you check it out, I'll be sure to update my project as well :)

**Comment by andypotato** [comment]
There's actually an easier solution. Instead of pinning the Tensorflow version, simply remove the tfjs-converter library. You can check out the [related commit on the Tensorflow models repository](https://github.com/tensorflow/tfjs-models/commit/1626c5ea1e0604628b2b8a9f39432e209c8465af#diff-373a15f9d1f9ed4b37e736f4dc688dbd).

I've also updated my example and readme file accordingly.

**Comment by LastLombax** [comment]
Does the new version of Handpose only work with the new version of Tensorflow?

**Comment by andypotato** [comment]
If you had it running using the pinned version 1.7.4 then I'd assume it runs with older versions too. Might need the converter lib though.
