### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by dwedaz** [andypotato/fingerpose#3]
Hi, I tried your example, but got this error.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://storage.googleapis.com/tfhub-tfjs-modules/mediapipe/tfjs-model/handdetector/1/default/1/model.json. (Reason: CORS request did not succeed).

**Comment by andypotato** [comment]
You need to run the demo from a local web server. Just opening the HTML file will not work.
