### ISSUE TITLE
Adding a Gesture Issue

### ISSUE THREAD

**Issue by the-other-clara** [andypotato/fingerpose#6]
Hello thank you for this awesome project !

I've launched your basic project locally using npm and i'm trying to add a new Gesture with your tutorial
I've edited all files according to your tutorial and created a description of my gesture  but i seem to have some issues with fingerpose.js. I've read 'Adding ThumbsDownGesture from README #1' and did a npm build but it doesn't work

When i'm listing the Gestures in my console, it creates a new Gesture but it's undefined and I have an error which says : 

Uncaught (in promise) TypeError: d is undefined
    value http://localhost:9000/fingerpose.js:1
    estimateHands http://localhost:9000/:130
fingerpose.js:1:9770

I'm sorry if that's a silly question i'm new to node
Thank you

**Comment by andypotato** [comment]
Hi, can you share your gesture definition and also the code where you add the gesture?

**Comment by the-other-clara** [comment]
Hello, here is what i added :

**Index.html**

 const gestureStrings = {
      'rock': '👊',
    };

 const knownGestures = [
        fp.Gestures.RockGesture
 ];

**Index.js**  

import RockGesture from './Rock';
export {
  RockGesture,
}

**Rock.js File** 

import { Finger, FingerCurl, FingerDirection } from '../FingerDescription';
import GestureDescription from '../GestureDescription';

const rockDescription = new GestureDescription('rock');

// all fingers are curled in a fist
for(let finger of [Finger.Index, Finger.Middle, Finger.Ring, Finger.Pinky, Finger.Thumb]) {
  rockDescription.addCurl(finger, FingerCurl.FullCurl, 1.0);
  rockDescription.addDirection(finger, FingerDirection.HorizontalLeft, 1.0);
  rockDescription.addDirection(finger, FingerDirection.HorizontalRight, 1.0);
}

export default rockDescription;

**Comment by MiloAkerman** [comment]
Having a similar problem here. Getting error `TypeError: Cannot read property 'matchAgainst' of undefined`

**Comment by MiloAkerman** [comment]
Nevermind! Was trying to input a gesture that didnt exist.

**Comment by willdow** [comment]
Hi, maybe you need to run `npm run build`

**Comment by mariovde** [comment]
Hi, 

I tried your rock pose, but can't get it to work:

fist.js
```
import { Finger, FingerCurl, FingerDirection } from "../FingerDescription";
import GestureDescription from "../GestureDescription";

// describe victory gesture ✌️
const fistDescription = new GestureDescription("fist");

// all fingers are curled in a fist
for (let finger of [
  Finger.Index,
  Finger.Middle,
  Finger.Ring,
  Finger.Pinky,
  Finger.Thumb,
]) {
  fistDescription.addCurl(finger, FingerCurl.FullCurl, 1.0);
  fistDescription.addDirection(finger, FingerDirection.HorizontalLeft, 1.0);
  fistDescription.addDirection(finger, FingerDirection.HorizontalRight, 1.0);
}

export default fistDescription;

```

gestures/index.js

```
import VictoryGesture from "./Victory";
import ThumbsUpGesture from "./ThumbsUp";
import FistGesture from "./Fist";
export { VictoryGesture, ThumbsUpGesture, FistGesture };

```


index.html
```

const knownGestures = [
          fp.Gestures.VictoryGesture,
          fp.Gestures.ThumbsUpGesture,
          fp.Gestures.FistGesture,
        ];
```

did you get it to work @MiloAkerman ?

**Comment by andypotato** [comment]
For the rock pose don't use "FullCurl" for the thumb - unless you have some kind of rubber bones the best you can do is half curl so you should adjust the expected pose for the thumb.

Also if you look at real people striking a "rock" pose, they might not even curl their thumb at all so I recommend to treat "no curl" and "half curl" with equal weights.
